// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Client_HopThu
{
    /// <summary>Badge chưa đọc trên tiêu đề trang.</summary>
    protected global::System.Web.UI.WebControls.Literal litBadgeHopThu;

    /// <summary>Tổng số cuộc hỏi.</summary>
    protected global::System.Web.UI.WebControls.Literal litTongCuoc;

    /// <summary>Số chưa đọc.</summary>
    protected global::System.Web.UI.WebControls.Literal litChuaDoc;

    /// <summary>Tổng phản hồi.</summary>
    protected global::System.Web.UI.WebControls.Literal litTongPhanHoi;

    /// <summary>Thông báo khi không có tư vấn nào.</summary>
    protected global::System.Web.UI.WebControls.Literal litEmpty;

    /// <summary>Danh sách tư vấn.</summary>
    protected global::System.Web.UI.WebControls.Repeater rptHopThu;

    /// <summary>HiddenField lưu mã tư vấn đang xem (để trigger JS mở modal).</summary>
    protected global::System.Web.UI.WebControls.HiddenField hfMaTuVan;

    /// <summary>Tên trường hiển thị trong header modal.</summary>
    protected global::System.Web.UI.WebControls.Literal litModalTruong;

    /// <summary>Thông tin meta của tư vấn (trường, ngày, trạng thái).</summary>
    protected global::System.Web.UI.WebControls.Literal litHopThuMeta;

    /// <summary>Nội dung câu hỏi gốc trong modal.</summary>
    protected global::System.Web.UI.WebControls.Literal litCauHoiGoc;

    /// <summary>Timeline thread tư vấn trong modal.</summary>
    protected global::System.Web.UI.WebControls.Repeater rptThread;

    /// <summary>Panel chứa reply box (ẩn khi tư vấn đóng).</summary>
    protected global::System.Web.UI.WebControls.Panel pnlReply;

    /// <summary>Thông báo sau khi gửi reply (success/error).</summary>
    protected global::System.Web.UI.WebControls.Literal litReplyMsg;

    /// <summary>Textbox nhập nội dung reply.</summary>
    protected global::System.Web.UI.WebControls.TextBox txtReply;

    /// <summary>Nút gửi reply.</summary>
    protected global::System.Web.UI.WebControls.Button btnGuiReply;
}
